version: '3.9'
services:
  coun-trivia-frontend:
    image: registry.gitlab.com/gibz/teaching/m347/countrivia/frontend:latest
    container_name: countrivia-frontend
    ports:
      - 80:80
    environment:
      - VITE_APP_COUNTRIVIA_API_BASE_URL=http://localhost:6301

  coun-trivia-backend:
    build: .
    container_name: countrivia-backend
    ports:
      - 6301:6301
    links:
      - coun-trivia-db
    environment:
      - REST_COUNTRIES_API_URL=https://restcountries.com/v3.1
      - ALTERNATIVE_ANSWER_COUNT=3
      - ALTERNATIVE_ANSWER_COUNT_VARIANCE=1
      - CounTriviaMariaDbInDocker=Database=countrivia;Server=coun-trivia-db;Port=3306;Uid=root;
    depends_on:
      coun-trivia-db:
        condition: service_healthy

  coun-trivia-db:
    image: mariadb:latest
    container_name: coun-trivia-db
    ports:
      - 3306:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=countrivia
      - MARIADB_DATABASE=countrivia
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su=root", "--innodb_initialized"]